### ISSUE TITLE
No updates in 6 month - is this library maintained anymore?

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-client-python#4]

**Comment by CermakM** [comment]
Hi @alexec,

I haven't been able to find any time lately to maintain this library. However, Yudi Xue (@binarycrayon) is willing to maintain both this repository and https://github.com/argoproj-labs/argo-python-dsl.

I've already added him as a maintainer to the Argo DSL, would you be so kind to do so for this one as well? I haven't got the privileges here.

**Comment by edlee2121** [comment]
Looks like the invitation has been sent to Yudi.

**Comment by binarycrayon** [comment]
Yes I have been added, thanks!

**Comment by edlee2121** [comment]
@binarycrayon It shows your invitation to join the SDK Maintainers team as still pending.
Could you check if you have accepted? Thanks

**Comment by binarycrayon** [comment]
@edlee2121 thanks for the nudge, I saw the email but never clicked on the button, I should be joined now
